use_frameworks!

target 'BradColorPicker_Example' do
  pod 'BradColorPicker', :path => '../'

  target 'BradColorPicker_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
